#!/bin/bash
echo "calc- you must write sum, div, mul or  sub and 2 arguments"
echo "search- you must write ditectory and string thay you want to search"
echo "reverse- you must write file you ant to reverse and file to write reverse information"
echo "strlen- you must write string and you get number of sumbols"
echo "log- you mustn't write anythink just log"
echo "exit- you must write word exit and return code"
echo "help- help)"
echo "interactive- programm turns into interactive way of work"
echo "exit codes"
echo "2- no or not enough arguments"
echo "3- not a number"
echo "4- can't div on 0"
echo "5- wrong argument"
echo "6- no such dir"
echo "7- no file"
echo "8- no script"
echo "9- can't write file"
